disabled_rules: # 执行时排除掉的规则
    - identifier_name
    - line_length
    - large_tuple
    - notification_center_detachment
    - multiple_closures_with_trailing_closure
    - block_based_kvo
    - nesting
    
opt_in_rules: # 某些规则默认是 disabled的, 需要的话放在这里启用
    - anyobject_protocol
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discouraged_none_name
    - discouraged_object_literal
    - empty_collection_literal
    - empty_string
    - empty_count
    - enum_case_associated_values_count
    - explicit_init
    - fallthrough
    - first_where
    - flatmap_over_map_reduce
    - identical_operands
    - last_where
    - legacy_random
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - modifier_order
    - number_separator
    - object_literal
    - operator_usage_whitespace
    - overridden_super_call
    - override_in_extension
    - prefer_self_type_over_type_of_self
    - private_action
    - private_outlet
    - prohibited_interface_builder
    - prohibited_super_call
    - quick_discouraged_call
    - reduce_into
    - redundant_nil_coalescing
    - sorted_first_last
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - vertical_parameter_alignment_on_call
    - yoda_condition

# 可以通过执行如下指令来查找所有可用的规则:
# swiftlint rules
# 详细规则解释和示例见: https://realm.github.io/SwiftLint/index.html

# 所有规则自定义内容对缩进要求非常严格, 注意官方文档.
# 规则文档: https://github.com/realm/SwiftLint#configuration
# 禁用指定代码位置规则不扫描 // swiftlint:disable <rule>

excluded: # 忽略检查的目录，优先级比 included 高
  - Carthage
  - Pods
  - .build

no_fallthrough_only:
  severity: error

force_cast:
  severity: error

empty_count:
  severity: error

cyclomatic_complexity:
  warning: 60
  error: 60

type_name:
  min_length: 
    warning: 2
    error: 2
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"] 

function_parameter_count:
  warning: 8
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 150
  error: 150

reporter: "xcode" # 报告类型 (xcode, json, csv, checkstyle, junit, html, emoji)
